services:

  app:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"

  db:
    build: ./.docker/mongodb
    container_name: mongodb-replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
